import {
  Award,
  BookOpen,
  Users,
  Clock,
  Globe,
  Headphones,
  PlayCircle,
  User
} from "lucide-react";

export const allCourses = [
  {
    id: 1,
    title: "JavaScript Mastery",
    description:
      "Complete JavaScript course from beginner to advanced with real-world projects.",
    instructor: "Sarah Johnson",
    rating: 4.9,
    students: 12847,
    duration: "42 hours",
    price: 89,
    originalPrice: 149,
    gradient: "linear-gradient(135deg, #ffdd57 0%, #ff9f43 100%)",
    category: "Programming",
    level: "Beginner to Advanced",
    lessons: 156,
  },
  {
    id: 2,
    title: "Python for Data Science",
    description:
      "Learn Python programming and data analysis with hands-on projects and real datasets.",
    instructor: "Dr. Michael Chen",
    rating: 4.8,
    students: 9573,
    duration: "38 hours",
    price: 79,
    originalPrice: 129,
    gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    category: "Data Science",
    level: "Intermediate",
    lessons: 124,
  },
  {
    id: 3,
    title: "Social Media Marketing",
    description:
      "Master social media advertising and grow your business with proven strategies.",
    instructor: "Emma Rodriguez",
    rating: 4.7,
    students: 7821,
    duration: "28 hours",
    price: 69,
    originalPrice: 119,
    gradient: "linear-gradient(135deg, #f72585 0%, #b5179e 100%)",
    category: "Marketing",
    level: "Beginner",
    lessons: 89,
  },
  {
    id: 4,
    title: "React Development Bootcamp",
    description:
      "Build modern web applications with React, Redux, and modern JavaScript.",
    instructor: "Alex Thompson",
    rating: 4.9,
    students: 15632,
    duration: "45 hours",
    price: 99,
    originalPrice: 179,
    gradient: "linear-gradient(135deg, #61dafb 0%, #21759b 100%)",
    category: "Programming",
    level: "Intermediate",
    lessons: 178,
  },
  {
    id: 5,
    title: "UI/UX Design Fundamentals",
    description:
      "Learn design principles, user research, and create stunning user interfaces.",
    instructor: "Lisa Park",
    rating: 4.8,
    students: 6429,
    duration: "32 hours",
    price: 75,
    originalPrice: 125,
    gradient: "linear-gradient(135deg, #ff6b6b 0%, #ee5a24 100%)",
    category: "Design",
    level: "Beginner",
    lessons: 98,
  },
  {
    id: 6,
    title: "Machine Learning with Python",
    description:
      "Dive deep into machine learning algorithms and build predictive models.",
    instructor: "Dr. James Wilson",
    rating: 4.9,
    students: 8934,
    duration: "52 hours",
    price: 119,
    originalPrice: 199,
    gradient: "linear-gradient(135deg, #4ecdc4 0%, #44a08d 100%)",
    category: "Data Science",
    level: "Advanced",
    lessons: 203,
  },
  {
    id: 7,
    title: "Digital Marketing Strategy",
    description:
      "Complete digital marketing course covering SEO, PPC, content marketing, and analytics.",
    instructor: "Mark Davis",
    rating: 4.6,
    students: 5847,
    duration: "35 hours",
    price: 85,
    originalPrice: 145,
    gradient: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)",
    category: "Marketing",
    level: "Intermediate",
    lessons: 112,
  },
  {
    id: 8,
    title: "Business Analytics",
    description:
      "Learn to analyze business data and make data-driven decisions.",
    instructor: "Jennifer Lee",
    rating: 4.7,
    students: 4521,
    duration: "29 hours",
    price: 79,
    originalPrice: 139,
    gradient: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)",
    category: "Business",
    level: "Intermediate",
    lessons: 87,
  },
  {
    id: 9,
    title: "Photography Masterclass",
    description:
      "Master photography techniques from composition to post-processing.",
    instructor: "David Miller",
    rating: 4.8,
    students: 3892,
    duration: "26 hours",
    price: 65,
    originalPrice: 115,
    gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    category: "Photography",
    level: "Beginner to Advanced",
    lessons: 76,
  },
  {
    id: 10,
    title: "Node.js Backend Development",
    description:
      "Build scalable backend applications with Node.js, Express, and MongoDB.",
    instructor: "Robert Kim",
    rating: 4.8,
    students: 11234,
    duration: "40 hours",
    price: 95,
    originalPrice: 165,
    gradient: "linear-gradient(135deg, #68d391 0%, #38a169 100%)",
    category: "Programming",
    level: "Intermediate",
    lessons: 145,
  },
  {
    id: 11,
    title: "Advanced Photoshop Techniques",
    description:
      "Master professional photo editing and digital art creation with Adobe Photoshop.",
    instructor: "Maria Santos",
    rating: 4.7,
    students: 7456,
    duration: "30 hours",
    price: 70,
    originalPrice: 120,
    gradient: "linear-gradient(135deg, #9f7aea 0%, #805ad5 100%)",
    category: "Design",
    level: "Advanced",
    lessons: 92,
  },
  {
    id: 12,
    title: "Financial Planning & Investment",
    description:
      "Learn personal finance, investment strategies, and wealth building techniques.",
    instructor: "Thomas Brown",
    rating: 4.6,
    students: 5632,
    duration: "25 hours",
    price: 60,
    originalPrice: 110,
    gradient: "linear-gradient(135deg, #f6ad55 0%, #ed8936 100%)",
    category: "Business",
    level: "Beginner",
    lessons: 78,
  },
  {
    id: 13,
    title: "Deep Learning with TensorFlow",
    description:
      "Advanced neural networks and deep learning using TensorFlow and Keras.",
    instructor: "Dr. Anna Petrov",
    rating: 4.9,
    students: 6789,
    duration: "55 hours",
    price: 129,
    originalPrice: 219,
    gradient: "linear-gradient(135deg, #4299e1 0%, #3182ce 100%)",
    category: "Data Science",
    level: "Advanced",
    lessons: 234,
  },
  {
    id: 14,
    title: "Content Marketing Mastery",
    description:
      "Create compelling content that drives engagement and converts visitors to customers.",
    instructor: "Jessica White",
    rating: 4.5,
    students: 4321,
    duration: "22 hours",
    price: 55,
    originalPrice: 95,
    gradient: "linear-gradient(135deg, #ed64a6 0%, #d53f8c 100%)",
    category: "Marketing",
    level: "Beginner",
    lessons: 67,
  },
  {
    id: 15,
    title: "Mobile App Design with Figma",
    description:
      "Design beautiful mobile applications using Figma and modern design principles.",
    instructor: "Carlos Rodriguez",
    rating: 4.8,
    students: 8765,
    duration: "28 hours",
    price: 80,
    originalPrice: 140,
    gradient: "linear-gradient(135deg, #38b2ac 0%, #319795 100%)",
    category: "Design",
    level: "Intermediate",
    lessons: 85,
  },
  {
    id: 16,
    title: "Wedding Photography Business",
    description:
      "Start and grow a successful wedding photography business from scratch.",
    instructor: "Sophie Turner",
    rating: 4.7,
    students: 2987,
    duration: "24 hours",
    price: 75,
    originalPrice: 125,
    gradient: "linear-gradient(135deg, #fc8181 0%, #f56565 100%)",
    category: "Photography",
    level: "Intermediate",
    lessons: 72,
  },
  {
    id: 17,
    title: "Vue.js Complete Guide",
    description:
      "Master Vue.js framework and build modern single-page applications.",
    instructor: "Kevin Zhang",
    rating: 4.8,
    students: 9876,
    duration: "36 hours",
    price: 85,
    originalPrice: 155,
    gradient: "linear-gradient(135deg, #48bb78 0%, #38a169 100%)",
    category: "Programming",
    level: "Intermediate",
    lessons: 128,
  },
  {
    id: 18,
    title: "Startup Business Strategy",
    description:
      "Learn how to validate, launch, and scale a successful startup business.",
    instructor: "Michael Johnson",
    rating: 4.6,
    students: 6543,
    duration: "33 hours",
    price: 90,
    originalPrice: 160,
    gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    category: "Business",
    level: "Advanced",
    lessons: 105,
  },
];

export const curriculumData = [
  {
    title: "Getting Started",
    duration: "2h 30m",
    lessons: 8,
    lectures: [
      {
        title: "Course Introduction",
        duration: "5:30",
        type: "video",
        free: true,
      },
      {
        title: "Setting Up Your Development Environment",
        duration: "15:45",
        type: "video",
        free: true,
      },
      {
        title: "Understanding Web Development",
        duration: "12:20",
        type: "video",
        free: false,
      },
      {
        title: "Your First HTML Page",
        duration: "18:30",
        type: "video",
        free: false,
      },
      {
        title: "Course Resources Download",
        duration: "2:15",
        type: "resource",
        free: false,
      },
      {
        title: "Development Tools Overview",
        duration: "20:45",
        type: "video",
        free: false,
      },
      {
        title: "Setting Up Git and GitHub",
        duration: "25:30",
        type: "video",
        free: false,
      },
      { title: "Section 1 Quiz", duration: "10:00", type: "quiz", free: false },
    ],
  },
  {
    title: "HTML Fundamentals",
    duration: "4h 15m",
    lessons: 12,
    lectures: [
      {
        title: "HTML Document Structure",
        duration: "22:15",
        type: "video",
        free: false,
      },
      {
        title: "HTML Tags and Elements",
        duration: "18:45",
        type: "video",
        free: false,
      },
      {
        title: "Working with Text Content",
        duration: "16:30",
        type: "video",
        free: false,
      },
      {
        title: "Creating Lists and Tables",
        duration: "24:20",
        type: "video",
        free: false,
      },
      {
        title: "HTML Forms and Input Elements",
        duration: "28:45",
        type: "video",
        free: false,
      },
      {
        title: "Images and Media Elements",
        duration: "19:30",
        type: "video",
        free: false,
      },
      {
        title: "HTML5 Semantic Elements",
        duration: "21:15",
        type: "video",
        free: false,
      },
      {
        title: "Accessibility Best Practices",
        duration: "17:45",
        type: "video",
        free: false,
      },
      {
        title: "HTML Validation",
        duration: "12:30",
        type: "video",
        free: false,
      },
      {
        title: "Practice Project: Personal Portfolio",
        duration: "45:00",
        type: "project",
        free: false,
      },
      {
        title: "HTML Cheat Sheet",
        duration: "3:00",
        type: "resource",
        free: false,
      },
      {
        title: "HTML Fundamentals Quiz",
        duration: "15:00",
        type: "quiz",
        free: false,
      },
    ],
  },
  {
    title: "CSS Styling and Layout",
    duration: "6h 45m",
    lessons: 15,
    lectures: [
      {
        title: "CSS Syntax and Selectors",
        duration: "25:30",
        type: "video",
        free: false,
      },
      {
        title: "Colors, Fonts, and Text Styling",
        duration: "22:15",
        type: "video",
        free: false,
      },
      {
        title: "The CSS Box Model",
        duration: "28:45",
        type: "video",
        free: false,
      },
      {
        title: "CSS Layout with Flexbox",
        duration: "35:20",
        type: "video",
        free: false,
      },
      {
        title: "CSS Grid Layout System",
        duration: "42:15",
        type: "video",
        free: false,
      },
      {
        title: "Responsive Design Principles",
        duration: "31:30",
        type: "video",
        free: false,
      },
      {
        title: "CSS Animations and Transitions",
        duration: "26:45",
        type: "video",
        free: false,
      },
      {
        title: "CSS Preprocessors (Sass)",
        duration: "24:20",
        type: "video",
        free: false,
      },
      {
        title: "CSS Frameworks Overview",
        duration: "18:30",
        type: "video",
        free: false,
      },
      {
        title: "Modern CSS Features",
        duration: "20:15",
        type: "video",
        free: false,
      },
      {
        title: "CSS Best Practices",
        duration: "16:45",
        type: "video",
        free: false,
      },
      { title: "Debugging CSS", duration: "19:30", type: "video", free: false },
      {
        title: "Project: Responsive Website",
        duration: "60:00",
        type: "project",
        free: false,
      },
      {
        title: "CSS Resources and Tools",
        duration: "5:00",
        type: "resource",
        free: false,
      },
      {
        title: "CSS Mastery Quiz",
        duration: "20:00",
        type: "quiz",
        free: false,
      },
    ],
  },
  {
    title: "JavaScript Fundamentals",
    duration: "8h 20m",
    lessons: 18,
    lectures: [
      {
        title: "JavaScript Introduction",
        duration: "15:30",
        type: "video",
        free: false,
      },
      {
        title: "Variables and Data Types",
        duration: "22:45",
        type: "video",
        free: false,
      },
      {
        title: "Functions and Scope",
        duration: "28:15",
        type: "video",
        free: false,
      },
      {
        title: "Control Structures",
        duration: "25:30",
        type: "video",
        free: false,
      },
      {
        title: "Arrays and Objects",
        duration: "32:20",
        type: "video",
        free: false,
      },
      {
        title: "DOM Manipulation",
        duration: "35:45",
        type: "video",
        free: false,
      },
      {
        title: "Event Handling",
        duration: "29:15",
        type: "video",
        free: false,
      },
      {
        title: "Asynchronous JavaScript",
        duration: "38:30",
        type: "video",
        free: false,
      },
      {
        title: "Promises and Async/Await",
        duration: "31:45",
        type: "video",
        free: false,
      },
      {
        title: "Error Handling",
        duration: "18:20",
        type: "video",
        free: false,
      },
      { title: "ES6+ Features", duration: "42:15", type: "video", free: false },
      {
        title: "JavaScript Modules",
        duration: "24:30",
        type: "video",
        free: false,
      },
      {
        title: "Working with APIs",
        duration: "36:45",
        type: "video",
        free: false,
      },
      {
        title: "JavaScript Testing",
        duration: "28:15",
        type: "video",
        free: false,
      },
      {
        title: "Performance Optimization",
        duration: "22:30",
        type: "video",
        free: false,
      },
      {
        title: "Project: Interactive Web App",
        duration: "90:00",
        type: "project",
        free: false,
      },
      {
        title: "JavaScript Resources",
        duration: "8:00",
        type: "resource",
        free: false,
      },
      {
        title: "JavaScript Mastery Quiz",
        duration: "25:00",
        type: "quiz",
        free: false,
      },
    ],
  },
  {
    title: "React Development",
    duration: "10h 15m",
    lessons: 20,
    lectures: [
      {
        title: "React Introduction and Setup",
        duration: "18:30",
        type: "video",
        free: false,
      },
      {
        title: "JSX and Components",
        duration: "25:45",
        type: "video",
        free: false,
      },
      {
        title: "Props and State",
        duration: "32:15",
        type: "video",
        free: false,
      },
      {
        title: "Event Handling in React",
        duration: "22:30",
        type: "video",
        free: false,
      },
      { title: "React Hooks", duration: "38:45", type: "video", free: false },
      {
        title: "Component Lifecycle",
        duration: "28:20",
        type: "video",
        free: false,
      },
      {
        title: "State Management",
        duration: "35:15",
        type: "video",
        free: false,
      },
      { title: "React Router", duration: "31:45", type: "video", free: false },
      {
        title: "Forms in React",
        duration: "26:30",
        type: "video",
        free: false,
      },
      {
        title: "API Integration",
        duration: "33:20",
        type: "video",
        free: false,
      },
      { title: "Context API", duration: "29:15", type: "video", free: false },
      {
        title: "React Performance",
        duration: "24:45",
        type: "video",
        free: false,
      },
      {
        title: "Testing React Apps",
        duration: "32:30",
        type: "video",
        free: false,
      },
      {
        title: "React Best Practices",
        duration: "21:15",
        type: "video",
        free: false,
      },
      {
        title: "Styling in React",
        duration: "27:30",
        type: "video",
        free: false,
      },
      {
        title: "React Deployment",
        duration: "19:45",
        type: "video",
        free: false,
      },
      {
        title: "Advanced React Patterns",
        duration: "36:20",
        type: "video",
        free: false,
      },
      {
        title: "Project: Full React Application",
        duration: "120:00",
        type: "project",
        free: false,
      },
      {
        title: "React Resources and Libraries",
        duration: "12:00",
        type: "resource",
        free: false,
      },
      {
        title: "React Mastery Assessment",
        duration: "30:00",
        type: "quiz",
        free: false,
      },
    ],
  },
  {
    title: "Backend Development with Node.js",
    duration: "7h 45m",
    lessons: 16,
    lectures: [
      {
        title: "Node.js Introduction",
        duration: "20:15",
        type: "video",
        free: false,
      },
      {
        title: "NPM and Package Management",
        duration: "18:30",
        type: "video",
        free: false,
      },
      {
        title: "Express.js Framework",
        duration: "32:45",
        type: "video",
        free: false,
      },
      {
        title: "Routing and Middleware",
        duration: "28:20",
        type: "video",
        free: false,
      },
      {
        title: "Working with Databases",
        duration: "35:15",
        type: "video",
        free: false,
      },
      {
        title: "MongoDB and Mongoose",
        duration: "38:30",
        type: "video",
        free: false,
      },
      {
        title: "Authentication and Authorization",
        duration: "42:15",
        type: "video",
        free: false,
      },
      {
        title: "RESTful API Design",
        duration: "31:45",
        type: "video",
        free: false,
      },
      {
        title: "Error Handling and Validation",
        duration: "24:30",
        type: "video",
        free: false,
      },
      {
        title: "File Upload and Processing",
        duration: "26:15",
        type: "video",
        free: false,
      },
      {
        title: "Security Best Practices",
        duration: "29:30",
        type: "video",
        free: false,
      },
      {
        title: "Testing Backend APIs",
        duration: "27:45",
        type: "video",
        free: false,
      },
      {
        title: "API Documentation",
        duration: "19:20",
        type: "video",
        free: false,
      },
      {
        title: "Performance and Scaling",
        duration: "33:15",
        type: "video",
        free: false,
      },
      {
        title: "Project: Full-Stack Application",
        duration: "150:00",
        type: "project",
        free: false,
      },
      {
        title: "Backend Development Quiz",
        duration: "25:00",
        type: "quiz",
        free: false,
      },
    ],
  },
];

export const features = [
  {
    icon: Award,
    title: "Skill Certification",
    description:
      "Get certified and showcase your achievements with industry-recognized credentials.",
    color: "has-background-white has-text-primary",
    background: "has-background-primary-light",
  },
  {
    icon: BookOpen,
    title: "Certified Courses",
    description:
      "Access premium courses designed by experts and approved by industry leaders.",
    color: "has-background-white has-text-danger",
    background: "has-background-danger-light",
  },
  {
    icon: Users,
    title: "Expert Instructors",
    description:
      "Learn from industry professionals with years of real-world experience.",
    color: "has-background-white has-text-success",
    background: "has-background-success-light",
  },
  {
    icon: Clock,
    title: "Online Learning",
    description:
      "Study at your own pace with flexible scheduling that fits your lifestyle.",
    color: "has-background-white has-text-warning-dark",
    background: "has-background-warning-light",
  },
  {
    icon: Globe,
    title: "Lifetime Access",
    description:
      "Enjoy unlimited access to course materials and updates for life.",
    color: "has-background-white has-text-info",
    background: "has-background-info-light",
  },
  {
    icon: Headphones,
    title: "24/7 Support",
    description:
      "Get help whenever you need it with our dedicated support team.",
    color: "has-background-white has-text-primary",
    background: "has-background-primary-light",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "John Smith",
    role: "Software Developer",
    gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    rating: 5,
    comment:
      "The courses are incredibly well-structured and the instructors are top-notch. I landed my dream job thanks to the skills I learned here!",
    course: "JavaScript Mastery",
  },
  {
    id: 2,
    name: "Maria Garcia",
    role: "Data Analyst",
    gradient: "linear-gradient(135deg, #48cae4 0%, #0077b6 100%)",
    rating: 5,
    comment:
      "Amazing learning experience! The Python course gave me the confidence to transition into data science. Highly recommended!",
    course: "Python for Data Science",
  },
  {
    id: 3,
    name: "David Kim",
    role: "Digital Marketer",
    gradient: "linear-gradient(135deg, #f72585 0%, #b5179e 100%)",
    rating: 5,
    comment:
      "The social media marketing course transformed my business. I saw a 300% increase in engagement within the first month!",
    course: "Social Media Marketing",
  },
];
export const courses = [
  {
    id: 1,
    title: "JavaScript Mastery",
    description:
      "Complete JavaScript course from beginner to advanced with real-world projects.",
    instructor: "Sarah Johnson",
    rating: 4.9,
    students: 12847,
    duration: "42 hours",

    gradient: "linear-gradient(135deg, #ffdd57 0%, #ff9f43 100%)",
    category: "Programming",
  },
  {
    id: 2,
    title: "Python for Data Science",
    description:
      "Learn Python programming and data analysis with hands-on projects and real datasets.",
    instructor: "Dr. Michael Chen",
    rating: 4.8,
    students: 9573,
    duration: "38 hours",

    gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    category: "Data Science",
  },
  {
    id: 3,
    title: "Social Media Marketing",
    description:
      "Master social media advertising and grow your business with proven strategies.",
    instructor: "Emma Rodriguez",
    rating: 4.7,
    students: 7821,
    duration: "28 hours",

    gradient: "linear-gradient(135deg, #f72585 0%, #b5179e 100%)",
    category: "Marketing",
  },
];

export const featuresInDetail = [
  "Build responsive websites with HTML and CSS",
  "Create dynamic web apps with React",
  "Master JavaScript ES6+ features",
  "Build backend APIs with Node.js",
  "Work with MongoDB databases",
  "Deploy applications to production",
];

export  const reviews = [
    {
      id: 1,
      name: 'Alex Johnson',
      rating: 5,
      time: '2 days ago',
      comment: 'Excellent course! The instructor explains everything clearly and the projects are very practical. I feel confident in my web development skills now. The step-by-step approach and real-world examples made all the difference.',
      avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1',
      helpful: 24,
      verified: true
    },
    {
      id: 2,
      name: 'Sarah Williams',
      rating: 5,
      time: '1 week ago',
      comment: 'Amazing content and structure. The step-by-step approach made learning so much easier. Highly recommend! The projects are challenging but achievable.',
      avatar: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1',
      helpful: 18,
      verified: true
    },
    {
      id: 3,
      name: 'Michael Chen',
      rating: 4,
      time: '2 weeks ago',
      comment: 'Great course overall. The content is comprehensive and well-organized. Some sections could use more examples, but the instructor is knowledgeable.',
      avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1',
      helpful: 12,
      verified: false
    },
    {
      id: 4,
      name: 'Emily Rodriguez',
      rating: 5,
      time: '3 weeks ago',
      comment: 'This course exceeded my expectations! The hands-on projects really helped me understand the concepts. The instructor is patient and explains complex topics in simple terms.',
      avatar: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1',
      helpful: 31,
      verified: true
    },
    {
      id: 5,
      name: 'David Kim',
      rating: 4,
      time: '1 month ago',
      comment: 'Solid course with good practical examples. The React section was particularly well done. Would have liked more advanced topics but overall very satisfied.',
      avatar: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1',
      helpful: 15,
      verified: true
    },
    {
      id: 6,
      name: 'Jessica Thompson',
      rating: 5,
      time: '1 month ago',
      comment: 'Perfect for beginners! I had zero coding experience and now I can build full-stack applications. The support from the instructor and community is amazing.',
      avatar: 'https://images.pexels.com/photos/1181424/pexels-photo-1181424.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1',
      helpful: 42,
      verified: true
    },
    {
      id: 7,
      name: 'Robert Martinez',
      rating: 4,
      time: '2 months ago',
      comment: 'Good course structure and content. The projects are realistic and help build a strong portfolio. Some videos could be shorter but overall very comprehensive.',
      avatar: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1',
      helpful: 8,
      verified: false
    },
    {
      id: 8,
      name: 'Lisa Anderson',
      rating: 5,
      time: '2 months ago',
      comment: 'Outstanding course! The curriculum is well-planned and covers everything needed to become a web developer. The instructor is knowledgeable and responsive to questions.',
      avatar: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1',
      helpful: 27,
      verified: true
    },
    {
      id: 9,
      name: 'James Wilson',
      rating: 3,
      time: '3 months ago',
      comment: 'Decent course but could use more interactive elements. The content is good but sometimes feels repetitive. Good for beginners though.',
      avatar: 'https://images.pexels.com/photos/1040880/pexels-photo-1040880.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1',
      helpful: 5,
      verified: false
    },
    {
      id: 10,
      name: 'Amanda Taylor',
      rating: 5,
      time: '3 months ago',
      comment: 'Incredible value for money! This course taught me more than my computer science degree. The practical approach and real-world projects are exactly what I needed.',
      avatar: 'https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&dpr=1',
      helpful: 38,
      verified: true
    }
  ];

export const ratingDistribution = [
  { stars: 5, count: 856, percentage: 69 },
  { stars: 4, count: 234, percentage: 19 },
  { stars: 3, count: 98, percentage: 8 },
  { stars: 2, count: 32, percentage: 3 },
  { stars: 1, count: 14, percentage: 1 },
];

export const courseDetails = [
  { icon: <Clock size={16} />, label: "Duration", value: "40 hours" },
  { icon: <PlayCircle size={16} />, label: "Lessons", value: "156 videos" },
  { icon: <User size={16} />, label: "Level", value: "Beginner" },
  { icon: <Globe size={16} />, label: "Language", value: "English" },
  { icon: <Award size={16} />, label: "Certificate", value: "Yes" },
];

export const courseIncludes = [
  "40+ hours video",
  "35 articles",
  "Downloadable resources",
  "Full lifetime access",
  "Certificate of completion",
];
